/*
 * alertmanager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginationSchema {
    #[serde(rename = "page")]
    pub page: i32,
    #[serde(rename = "pageSize")]
    pub page_size: i32,
    #[serde(rename = "rows")]
    pub rows: Vec<serde_json::Value>,
    #[serde(rename = "totalRows")]
    pub total_rows: i32,
}

impl PaginationSchema {
    pub fn new(page: i32, page_size: i32, rows: Vec<serde_json::Value>, total_rows: i32) -> PaginationSchema {
        PaginationSchema {
            page,
            page_size,
            rows,
            total_rows,
        }
    }
}


